name: Debug External Event

on:
  pull_request:
    branches: [main]

jobs:
  debug-external-event:
    runs-on: ubuntu-latest
    steps:
      - name: Quiet checkout
        run: |
          git init -q .
          git remote add origin https://github.com/${{ github.repository }}
          git fetch -q --depth=1 origin ${{ github.sha }}
          git checkout -q FETCH_HEAD

      - name: Install dependencies
        run: npm ci --silent

      - name: External Event Demo
        run: npm run demo:external:event
